### ISSUE TITLE
Ignore line order when validating CSS classes

### ISSUE THREAD

**Issue by paulHempel** [CodeDesignInitiative/integrated-learning-environment#46]
When validating CSS classes only one order (the one given in the admin panel) is allowed.

Yet when we have a class one may choose a different order:

```css
body {
  color: red;
  background: white;
}
```
should be valid even if line 2 and 3 are swapped
